2019-08-03 21:39:59,320 ERROR Exception on /reset_password_request [GET] [in c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py:(lineno)d]
Traceback (most recent call last):
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\Documents\microblog\app\routes.py", line 268, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\user\Documents\microblog\app\templates\reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\user\Documents\microblog\app\templates\base.html", line 36, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\user\Documents\microblog\app\templates\reset_password_request.html", line 8, in block "content"
    {{ form.email.label }}<br>
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordForm object' has no attribute 'email'
2019-08-03 21:43:56,508 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-08-03 21:44:06,689 ERROR Exception on /reset_password_request [GET] [in c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py:(lineno)d]
Traceback (most recent call last):
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\Documents\microblog\app\routes.py", line 268, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\user\Documents\microblog\app\templates\reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\user\Documents\microblog\app\templates\base.html", line 36, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\user\Documents\microblog\app\templates\reset_password_request.html", line 8, in block "content"
    {{ form.email.label }}<br>
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordForm object' has no attribute 'email'
2019-08-03 21:44:22,718 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-08-03 21:44:28,766 ERROR Exception on /reset_password_request [GET] [in c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py:(lineno)d]
Traceback (most recent call last):
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\Documents\microblog\app\routes.py", line 268, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\user\Documents\microblog\app\templates\reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\user\Documents\microblog\app\templates\base.html", line 36, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\user\Documents\microblog\app\templates\reset_password_request.html", line 8, in block "content"
    {{ form.email.label }}<br>
  File "c:\users\user\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordForm object' has no attribute 'email'
2019-08-03 21:51:34,338 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
